### ISSUE TITLE
Core dump when trying to execute `git clone` in this image.

### ISSUE THREAD

**Issue by jemc** [edib-tool/docker-base-dev#2]
I'm trying to use the `edib/edib-tool:1.6.0` docker image to build my release.

My `mix.exs` has some `git` dependencies, but when `git` is invoked in the container, it fails and writes a core dump file to the current working directory.  When run a shell in the container and invoke `git clone` myself, I get the same result - failure, and a core dump

I traced it back to the `edib/base-dev:3.4` docker image, which has the same problem.  You can reproduce with:

```
$ docker run -ti --rm edib/base-dev:3.4 sh

/ # cd /tmp
/tmp # git clone https://github.com/github/hub && echo okay! || echo failed!
Cloning into 'hub'...
failed!
/tmp # ls
core.4193
```

The `Dockerfile` looks fine, so the image on Docker Hub may be corrupted somehow.

I'd recommend rebuilding the image with a new version tag, and propagate new version tags all the way up to `edib/edib-tool:1.6.1` for the edib tool itself.

**Comment by asaaki** [comment]
No active development.
